In [166]:
import os
os.getcwd()

'/home/jovyan'

In [208]:
# Load data shipping data into a pandas dataframe
import pandas as pd
path_1 = "Spark/ACSST1Y2022.S1901-Data.csv"
household_income_df = pd.read_csv(path_1)
household_income_df

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,...,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M,Unnamed: 130
0,Geography,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000",Margin of Error!!Households!!Total!!Less than ...,"Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to...","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to...",...,Margin of Error!!Nonfamily households!!Median ...,Estimate!!Nonfamily households!!Mean income (d...,Margin of Error!!Nonfamily households!!Mean in...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,NaN
1,0400000US01,Alabama,2016448,11475,7.6,0.3,5.2,0.3,9.3,0.3,...,919,47145,1778,(X),(X),(X),(X),34.2,(X),NaN
2,0400000US02,Alaska,274574,3261,4.4,0.7,2.5,0.4,5.4,0.8,...,5211,74242,4733,(X),(X),(X),(X),30.3,(X),NaN
3,0400000US04,Arizona,2850377,11519,5.4,0.3,3.0,0.2,6.2,0.3,...,1067,66724,1965,(X),(X),(X),(X),33.6,(X),NaN
4,0400000US05,Arkansas,1216207,8435,7.3,0.5,5.9,0.4,9.5,0.4,...,773,45384,1596,(X),(X),(X),(X),34.4,(X),NaN
5,0400000US06,California,13550586,19485,4.8,0.1,3.2,0.1,5.5,0.1,...,751,89374,995,(X),(X),(X),(X),33.3,(X),NaN
6,0400000US08,Colorado,2384584,7807,4.1,0.2,2.5,0.2,5.4,0.3,...,1653,77519,1515,(X),(X),(X),(X),30.8,(X),NaN
7,0400000US09,Connecticut,1433635,7120,5.1,0.4,3.2,0.3,5.9,0.4,...,1374,72770,2549,(X),(X),(X),(X),33.8,(X),NaN
8,0400000US10,Delaware,402334,3985,4.0,0.6,2.6,0.5,5.8,0.6,...,2718,62657,2400,(X),(X),(X),(X),29.7,(X),NaN
9,0400000US11,District of Columbia,326970,3481,6.8,1.0,2.8,0.6,5.1,1.0,...,3796,112447,5167,(X),(X),(X),(X),24.0,(X),NaN
10,0400000US12,Florida,8826394,23013,5.6,0.2,3.5,0.1,7.2,0.2,...,612,64627,1040,(X),(X),(X),(X),33.1,(X),NaN
11,0400000US13,Georgia,4092467,12679,5.6,0.2,3.6,0.2,6.9,0.2,...,924,61965,928,(X),(X),(X),(X),35.5,(X),NaN
12,0400000US15,Hawaii,494827,4463,5.3,0.6,2.6,0.3,5.1,0.5,...,2199,76308,3514,(X),(X),(X),(X),31.9,(X),NaN
13,0400000US16,Idaho,717151,4796,3.8,0.3,3.4,0.4,6.5,0.5,...,1724,57863,2581,(X),(X),(X),(X),32.3,(X),NaN
14,0400000US17,Illinois,5056360,12532,5.9,0.2,3.5,0.1,6.5,0.2,...,744,65371,1109,(X),(X),(X),(X),33.3,(X),NaN
15,0400000US18,Indiana,2726489,11359,5.6,0.2,3.8,0.2,7.1,0.3,...,699,53033,949,(X),(X),(X),(X),32.2,(X),NaN
16,0400000US19,Iowa,1330995,5631,4.3,0.3,3.6,0.3,7.5,0.4,...,811,54531,1551,(X),(X),(X),(X),31.5,(X),NaN
17,0400000US20,Kansas,1175294,6195,5.3,0.4,3.6,0.3,7.5,0.4,...,1255,54058,1716,(X),(X),(X),(X),32.3,(X),NaN
18,0400000US21,Kentucky,1828680,8263,6.8,0.3,5.8,0.3,8.9,0.3,...,894,48151,1555,(X),(X),(X),(X),30.6,(X),NaN
19,0400000US22,Louisiana,1816902,10634,7.9,0.4,6.0,0.3,10.2,0.5,...,864,47270,1336,(X),(X),(X),(X),35.5,(X),NaN
20,0400000US23,Maine,605338,5032,4.7,0.5,4.0,0.4,7.6,0.5,...,1513,55434,2071,(X),(X),(X),(X),31.2,(X),NaN
21,0400000US24,Maryland,2375984,8175,4.8,0.3,2.6,0.2,4.9,0.3,...,1731,77318,1849,(X),(X),(X),(X),32.8,(X),NaN
22,0400000US25,Massachusetts,2797776,8835,5.2,0.2,3.6,0.2,5.6,0.2,...,1580,82617,1855,(X),(X),(X),(X),34.5,(X),NaN
23,0400000US26,Michigan,4089794,11504,5.7,0.2,4.0,0.2,7.6,0.2,...,543,56097,982,(X),(X),(X),(X),33.5,(X),NaN
24,0400000US27,Minnesota,2322190,6929,4.3,0.3,3.1,0.2,5.6,0.2,...,1190,65533,1417,(X),(X),(X),(X),29.8,(X),NaN
25,0400000US28,Mississippi,1148340,8056,8.1,0.4,6.4,0.4,10.6,0.4,...,1309,40989,1658,(X),(X),(X),(X),34.9,(X),NaN
26,0400000US29,Missouri,2521832,11480,5.7,0.2,4.4,0.2,7.7,0.3,...,948,52852,1171,(X),(X),(X),(X),32.7,(X),NaN
27,0400000US30,Montana,464072,4326,5.0,0.5,4.4,0.5,7.4,0.6,...,1321,58278,2523,(X),(X),(X),(X),32.2,(X),NaN
28,0400000US31,Nebraska,803157,3991,4.9,0.4,3.4,0.4,7.4,0.5,...,914,54076,2074,(X),(X),(X),(X),30.6,(X),NaN
29,0400000US32,Nevada,1198356,7074,5.6,0.4,3.1,0.3,6.5,0.5,...,1218,66078,2226,(X),(X),(X),(X),34.4,(X),NaN
30,0400000US33,New Hampshire,557220,4834,3.1,0.4,2.8,0.4,5.3,0.6,...,1703,75262,3536,(X),(X),(X),(X),30.2,(X),NaN
31,0400000US34,New Jersey,3516978,9044,4.4,0.2,2.9,0.2,5.0,0.2,...,1202,78512,1893,(X),(X),(X),(X),33.4,(X),NaN
32,0400000US35,New Mexico,848218,4975,7.4,0.6,4.9,0.4,9.5,0.6,...,1339,55207,2176,(X),(X),(X),(X),30.7,(X),NaN
33,0400000US36,New York,7774308,19481,6.8,0.2,4.1,0.2,6.7,0.2,...,780,78600,1257,(X),(X),(X),(X),36.4,(X),NaN
34,0400000US37,North Carolina,4299266,15150,5.4,0.2,4.0,0.2,7.4,0.2,...,469,58122,969,(X),(X),(X),(X),32.6,(X),NaN
35,0400000US38,North Dakota,331481,3670,5.0,0.7,4.0,0.7,6.6,0.7,...,1791,55371,2771,(X),(X),(X),(X),30.9,(X),NaN
36,0400000US39,Ohio,4878206,13413,5.9,0.2,4.4,0.2,7.5,0.2,...,580,54221,783,(X),(X),(X),(X),30.7,(X),NaN
37,0400000US40,Oklahoma,1573180,5742,6.4,0.3,4.6,0.3,9.2,0.3,...,842,49318,1225,(X),(X),(X),(X),34.1,(X),NaN
38,0400000US41,Oregon,1726340,6662,5.1,0.3,3.4,0.3,6.9,0.3,...,1595,66755,1634,(X),(X),(X),(X),28.7,(X),NaN
39,0400000US42,Pennsylvania,5294065,14260,5.5,0.2,3.7,0.1,7.3,0.2,...,636,60489,1072,(X),(X),(X),(X),32.9,(X),NaN
40,0400000US44,Rhode Island,446688,3663,5.4,0.7,4.3,0.7,6.2,0.7,...,3033,65595,3112,(X),(X),(X),(X),36.3,(X),NaN
41,0400000US45,South Carolina,2136080,11784,6.1,0.3,4.2,0.3,7.8,0.3,...,805,53647,1611,(X),(X),(X),(X),36.2,(X),NaN
42,0400000US46,South Dakota,368300,3163,5.0,0.6,3.8,0.4,7.3,0.7,...,1473,57250,3600,(X),(X),(X),(X),31.0,(X),NaN
43,0400000US47,Tennessee,2846684,11934,5.4,0.3,4.3,0.2,7.8,0.3,...,651,56860,1331,(X),(X),(X),(X),34.2,(X),NaN
44,0400000US48,Texas,11087708,20293,5.5,0.1,3.6,0.1,6.6,0.2,...,586,64874,806,(X),(X),(X),(X),30.6,(X),NaN
45,0400000US49,Utah,1129660,5750,3.0,0.3,2.4,0.3,4.1,0.3,...,1620,69275,2365,(X),(X),(X),(X),32.3,(X),NaN
46,0400000US50,Vermont,277090,3178,4.0,0.5,3.8,0.6,6.7,0.8,...,1963,63143,2776,(X),(X),(X),(X),31.0,(X),NaN
47,0400000US51,Virginia,3380607,12353,4.9,0.2,3.2,0.2,5.8,0.2,...,772,73302,1440,(X),(X),(X),(X),32.4,(X),NaN
48,0400000US53,Washington,3079953,10236,4.5,0.2,2.8,0.2,4.9,0.2,...,1187,84851,1987,(X),(X),(X),(X),29.1,(X),NaN
49,0400000US54,West Virginia,736341,6960,7.1,0.5,6.3,0.5,10.5,0.6,...,879,48384,3043,(X),(X),(X),(X),29.3,(X),NaN
50,0400000US55,Wisconsin,2491121,7766,4.6,0.2,3.5,0.2,7.0,0.2,...,841,57892,1109,(X),(X),(X),(X),28.7,(X),NaN
51,0400000US56,Wyoming,243321,3844,5.2,0.9,3.4,0.7,7.5,0.9,...,2776,57301,3886,(X),(X),(X),(X),28.8,(X),NaN
52,0400000US72,Puerto Rico,1289311,9077,22.4,0.6,10.8,0.5,18.2,0.6,...,414,24694,893,(X),(X),(X),(X),28.2,(X),NaN

In [209]:
# Apply the column renaming directly to the original data_df (excluding the first header row in data_df)
household_income_df.columns = household_income_df.iloc[0]  # Use the first row as column headers
household_income_df = household_income_df[1:]  # Drop the first row now that it's been used for column names

# Since the first row of data_df is now the column names, we need to adjust the column names based on the metadata
# Creating a new mapping since the original data_df had its columns replaced by the first row
new_column_mapping = {code: label for code, label in zip(household_income_df.columns, metadata_df['Label'])}

# Rename the columns in data_df using the new mapping
household_income_df.rename(columns=new_column_mapping, inplace=True)

# Display the first few rows of the now correctly named data_df to confirm
# Reset the indexes 
household_income_df.reset_index(drop=True, inplace=True)

/tmp/ipykernel_80/1000401046.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  household_income_df.rename(columns=new_column_mapping, inplace=True)

In [210]:
# Convert all column names to strings
household_income_df.columns = household_income_df.columns.astype(str)

household_income_df= household_income_df.rename(columns={'Geographic Area Name': 'State'})
household_income_df.columns = [str(col).replace("!!", "_") for col in household_income_df.columns]

household_income_df

,Geography,State,Estimate_Households_Total,Margin of Error_Households_Total,"Estimate_Households_Total_Less than $10,000","Margin of Error_Households_Total_Less than $10,000","Estimate_Households_Total_$10,000 to $14,999","Margin of Error_Households_Total_$10,000 to $14,999","Estimate_Households_Total_$15,000 to $24,999","Margin of Error_Households_Total_$15,000 to $24,999",...,Margin of Error_Nonfamily households_Median income (dollars),Estimate_Nonfamily households_Mean income (dollars),Margin of Error_Nonfamily households_Mean income (dollars),Estimate_Nonfamily households_PERCENT ALLOCATED_Household income in the past 12 months,Margin of Error_Nonfamily households_PERCENT ALLOCATED_Household income in the past 12 months,Estimate_Nonfamily households_PERCENT ALLOCATED_Family income in the past 12 months,Margin of Error_Nonfamily households_PERCENT ALLOCATED_Family income in the past 12 months,Estimate_Nonfamily households_PERCENT ALLOCATED_Nonfamily income in the past 12 months,Margin of Error_Nonfamily households_PERCENT ALLOCATED_Nonfamily income in the past 12 months,nan
0,0400000US01,Alabama,2016448,11475,7.6,0.3,5.2,0.3,9.3,0.3,...,919,47145,1778,(X),(X),(X),(X),34.2,(X),NaN
1,0400000US02,Alaska,274574,3261,4.4,0.7,2.5,0.4,5.4,0.8,...,5211,74242,4733,(X),(X),(X),(X),30.3,(X),NaN
2,0400000US04,Arizona,2850377,11519,5.4,0.3,3.0,0.2,6.2,0.3,...,1067,66724,1965,(X),(X),(X),(X),33.6,(X),NaN
3,0400000US05,Arkansas,1216207,8435,7.3,0.5,5.9,0.4,9.5,0.4,...,773,45384,1596,(X),(X),(X),(X),34.4,(X),NaN
4,0400000US06,California,13550586,19485,4.8,0.1,3.2,0.1,5.5,0.1,...,751,89374,995,(X),(X),(X),(X),33.3,(X),NaN
5,0400000US08,Colorado,2384584,7807,4.1,0.2,2.5,0.2,5.4,0.3,...,1653,77519,1515,(X),(X),(X),(X),30.8,(X),NaN
6,0400000US09,Connecticut,1433635,7120,5.1,0.4,3.2,0.3,5.9,0.4,...,1374,72770,2549,(X),(X),(X),(X),33.8,(X),NaN
7,0400000US10,Delaware,402334,3985,4.0,0.6,2.6,0.5,5.8,0.6,...,2718,62657,2400,(X),(X),(X),(X),29.7,(X),NaN
8,0400000US11,District of Columbia,326970,3481,6.8,1.0,2.8,0.6,5.1,1.0,...,3796,112447,5167,(X),(X),(X),(X),24.0,(X),NaN
9,0400000US12,Florida,8826394,23013,5.6,0.2,3.5,0.1,7.2,0.2,...,612,64627,1040,(X),(X),(X),(X),33.1,(X),NaN
10,0400000US13,Georgia,4092467,12679,5.6,0.2,3.6,0.2,6.9,0.2,...,924,61965,928,(X),(X),(X),(X),35.5,(X),NaN
11,0400000US15,Hawaii,494827,4463,5.3,0.6,2.6,0.3,5.1,0.5,...,2199,76308,3514,(X),(X),(X),(X),31.9,(X),NaN
12,0400000US16,Idaho,717151,4796,3.8,0.3,3.4,0.4,6.5,0.5,...,1724,57863,2581,(X),(X),(X),(X),32.3,(X),NaN
13,0400000US17,Illinois,5056360,12532,5.9,0.2,3.5,0.1,6.5,0.2,...,744,65371,1109,(X),(X),(X),(X),33.3,(X),NaN
14,0400000US18,Indiana,2726489,11359,5.6,0.2,3.8,0.2,7.1,0.3,...,699,53033,949,(X),(X),(X),(X),32.2,(X),NaN
15,0400000US19,Iowa,1330995,5631,4.3,0.3,3.6,0.3,7.5,0.4,...,811,54531,1551,(X),(X),(X),(X),31.5,(X),NaN
16,0400000US20,Kansas,1175294,6195,5.3,0.4,3.6,0.3,7.5,0.4,...,1255,54058,1716,(X),(X),(X),(X),32.3,(X),NaN
17,0400000US21,Kentucky,1828680,8263,6.8,0.3,5.8,0.3,8.9,0.3,...,894,48151,1555,(X),(X),(X),(X),30.6,(X),NaN
18,0400000US22,Louisiana,1816902,10634,7.9,0.4,6.0,0.3,10.2,0.5,...,864,47270,1336,(X),(X),(X),(X),35.5,(X),NaN
19,0400000US23,Maine,605338,5032,4.7,0.5,4.0,0.4,7.6,0.5,...,1513,55434,2071,(X),(X),(X),(X),31.2,(X),NaN
20,0400000US24,Maryland,2375984,8175,4.8,0.3,2.6,0.2,4.9,0.3,...,1731,77318,1849,(X),(X),(X),(X),32.8,(X),NaN
21,0400000US25,Massachusetts,2797776,8835,5.2,0.2,3.6,0.2,5.6,0.2,...,1580,82617,1855,(X),(X),(X),(X),34.5,(X),NaN
22,0400000US26,Michigan,4089794,11504,5.7,0.2,4.0,0.2,7.6,0.2,...,543,56097,982,(X),(X),(X),(X),33.5,(X),NaN
23,0400000US27,Minnesota,2322190,6929,4.3,0.3,3.1,0.2,5.6,0.2,...,1190,65533,1417,(X),(X),(X),(X),29.8,(X),NaN
24,0400000US28,Mississippi,1148340,8056,8.1,0.4,6.4,0.4,10.6,0.4,...,1309,40989,1658,(X),(X),(X),(X),34.9,(X),NaN
25,0400000US29,Missouri,2521832,11480,5.7,0.2,4.4,0.2,7.7,0.3,...,948,52852,1171,(X),(X),(X),(X),32.7,(X),NaN
26,0400000US30,Montana,464072,4326,5.0,0.5,4.4,0.5,7.4,0.6,...,1321,58278,2523,(X),(X),(X),(X),32.2,(X),NaN
27,0400000US31,Nebraska,803157,3991,4.9,0.4,3.4,0.4,7.4,0.5,...,914,54076,2074,(X),(X),(X),(X),30.6,(X),NaN
28,0400000US32,Nevada,1198356,7074,5.6,0.4,3.1,0.3,6.5,0.5,...,1218,66078,2226,(X),(X),(X),(X),34.4,(X),NaN
29,0400000US33,New Hampshire,557220,4834,3.1,0.4,2.8,0.4,5.3,0.6,...,1703,75262,3536,(X),(X),(X),(X),30.2,(X),NaN
30,0400000US34,New Jersey,3516978,9044,4.4,0.2,2.9,0.2,5.0,0.2,...,1202,78512,1893,(X),(X),(X),(X),33.4,(X),NaN
31,0400000US35,New Mexico,848218,4975,7.4,0.6,4.9,0.4,9.5,0.6,...,1339,55207,2176,(X),(X),(X),(X),30.7,(X),NaN
32,0400000US36,New York,7774308,19481,6.8,0.2,4.1,0.2,6.7,0.2,...,780,78600,1257,(X),(X),(X),(X),36.4,(X),NaN
33,0400000US37,North Carolina,4299266,15150,5.4,0.2,4.0,0.2,7.4,0.2,...,469,58122,969,(X),(X),(X),(X),32.6,(X),NaN
34,0400000US38,North Dakota,331481,3670,5.0,0.7,4.0,0.7,6.6,0.7,...,1791,55371,2771,(X),(X),(X),(X),30.9,(X),NaN
35,0400000US39,Ohio,4878206,13413,5.9,0.2,4.4,0.2,7.5,0.2,...,580,54221,783,(X),(X),(X),(X),30.7,(X),NaN
36,0400000US40,Oklahoma,1573180,5742,6.4,0.3,4.6,0.3,9.2,0.3,...,842,49318,1225,(X),(X),(X),(X),34.1,(X),NaN
37,0400000US41,Oregon,1726340,6662,5.1,0.3,3.4,0.3,6.9,0.3,...,1595,66755,1634,(X),(X),(X),(X),28.7,(X),NaN
38,0400000US42,Pennsylvania,5294065,14260,5.5,0.2,3.7,0.1,7.3,0.2,...,636,60489,1072,(X),(X),(X),(X),32.9,(X),NaN
39,0400000US44,Rhode Island,446688,3663,5.4,0.7,4.3,0.7,6.2,0.7,...,3033,65595,3112,(X),(X),(X),(X),36.3,(X),NaN
40,0400000US45,South Carolina,2136080,11784,6.1,0.3,4.2,0.3,7.8,0.3,...,805,53647,1611,(X),(X),(X),(X),36.2,(X),NaN
41,0400000US46,South Dakota,368300,3163,5.0,0.6,3.8,0.4,7.3,0.7,...,1473,57250,3600,(X),(X),(X),(X),31.0,(X),NaN
42,0400000US47,Tennessee,2846684,11934,5.4,0.3,4.3,0.2,7.8,0.3,...,651,56860,1331,(X),(X),(X),(X),34.2,(X),NaN
43,0400000US48,Texas,11087708,20293,5.5,0.1,3.6,0.1,6.6,0.2,...,586,64874,806,(X),(X),(X),(X),30.6,(X),NaN
44,0400000US49,Utah,1129660,5750,3.0,0.3,2.4,0.3,4.1,0.3,...,1620,69275,2365,(X),(X),(X),(X),32.3,(X),NaN
45,0400000US50,Vermont,277090,3178,4.0,0.5,3.8,0.6,6.7,0.8,...,1963,63143,2776,(X),(X),(X),(X),31.0,(X),NaN
46,0400000US51,Virginia,3380607,12353,4.9,0.2,3.2,0.2,5.8,0.2,...,772,73302,1440,(X),(X),(X),(X),32.4,(X),NaN
47,0400000US53,Washington,3079953,10236,4.5,0.2,2.8,0.2,4.9,0.2,...,1187,84851,1987,(X),(X),(X),(X),29.1,(X),NaN
48,0400000US54,West Virginia,736341,6960,7.1,0.5,6.3,0.5,10.5,0.6,...,879,48384,3043,(X),(X),(X),(X),29.3,(X),NaN
49,0400000US55,Wisconsin,2491121,7766,4.6,0.2,3.5,0.2,7.0,0.2,...,841,57892,1109,(X),(X),(X),(X),28.7,(X),NaN
50,0400000US56,Wyoming,243321,3844,5.2,0.9,3.4,0.7,7.5,0.9,...,2776,57301,3886,(X),(X),(X),(X),28.8,(X),NaN
51,0400000US72,Puerto Rico,1289311,9077,22.4,0.6,10.8,0.5,18.2,0.6,...,414,24694,893,(X),(X),(X),(X),28.2,(X),NaN

In [211]:
# Filter columns: Keep only those that do not start with "Margin of Error"
filtered_columns = [col for col in household_income_df.columns if not col.startswith("Margin of Error")]

# Apply the filter to the DataFrame
household_income_df = household_income_df[filtered_columns]
household_income_df = household_income_df.drop(columns=["Geography"])
household_income_df

,State,Estimate_Households_Total,"Estimate_Households_Total_Less than $10,000","Estimate_Households_Total_$10,000 to $14,999","Estimate_Households_Total_$15,000 to $24,999","Estimate_Households_Total_$25,000 to $34,999","Estimate_Households_Total_$35,000 to $49,999","Estimate_Households_Total_$50,000 to $74,999","Estimate_Households_Total_$75,000 to $99,999","Estimate_Households_Total_$100,000 to $149,999",...,"Estimate_Nonfamily households_Total_$75,000 to $99,999","Estimate_Nonfamily households_Total_$100,000 to $149,999","Estimate_Nonfamily households_Total_$150,000 to $199,999","Estimate_Nonfamily households_Total_$200,000 or more",Estimate_Nonfamily households_Median income (dollars),Estimate_Nonfamily households_Mean income (dollars),Estimate_Nonfamily households_PERCENT ALLOCATED_Household income in the past 12 months,Estimate_Nonfamily households_PERCENT ALLOCATED_Family income in the past 12 months,Estimate_Nonfamily households_PERCENT ALLOCATED_Nonfamily income in the past 12 months,nan
0,Alabama,2016448,7.6,5.2,9.3,8.6,12.0,16.7,12.6,14.9,...,8.1,5.7,1.9,1.6,32330,47145,(X),(X),34.2,NaN
1,Alaska,274574,4.4,2.5,5.4,5.3,9.1,15.8,13.2,21.8,...,13.1,15.9,4.7,4.3,57657,74242,(X),(X),30.3,NaN
2,Arizona,2850377,5.4,3.0,6.2,7.3,11.0,17.3,13.8,17.8,...,10.8,10.8,4.1,3.8,47840,66724,(X),(X),33.6,NaN
3,Arkansas,1216207,7.3,5.9,9.5,9.1,13.5,18.1,12.6,13.4,...,7.0,5.4,1.5,1.8,31230,45384,(X),(X),34.4,NaN
4,California,13550586,4.8,3.2,5.5,5.9,8.5,13.8,12.0,17.6,...,11.2,13.8,6.8,9.2,59348,89374,(X),(X),33.3,NaN
5,Colorado,2384584,4.1,2.5,5.4,5.8,9.2,15.1,13.4,19.0,...,12.9,13.7,5.5,5.9,57553,77519,(X),(X),30.8,NaN
6,Connecticut,1433635,5.1,3.2,5.9,6.0,8.7,13.8,12.6,17.7,...,11.8,13.5,4.5,4.5,50964,72770,(X),(X),33.8,NaN
7,Delaware,402334,4.0,2.6,5.8,7.1,10.4,15.9,13.9,20.0,...,12.3,11.2,2.9,3.3,46579,62657,(X),(X),29.7,NaN
8,District of Columbia,326970,6.8,2.8,5.1,4.6,7.0,12.3,10.7,16.6,...,13.1,16.9,9.7,14.1,82505,112447,(X),(X),24.0,NaN
9,Florida,8826394,5.6,3.5,7.2,8.0,11.7,17.4,13.4,16.0,...,10.3,9.1,3.6,3.9,43665,64627,(X),(X),33.1,NaN
10,Georgia,4092467,5.6,3.6,6.9,7.3,11.2,16.8,13.3,16.9,...,10.4,10.5,3.7,3.1,44656,61965,(X),(X),35.5,NaN
11,Hawaii,494827,5.3,2.6,5.1,5.2,8.6,14.8,12.0,20.1,...,11.1,12.6,5.3,5.5,53295,76308,(X),(X),31.9,NaN
12,Idaho,717151,3.8,3.4,6.5,7.6,11.5,19.0,15.4,18.0,...,9.1,8.5,2.6,2.4,42145,57863,(X),(X),32.3,NaN
13,Illinois,5056360,5.9,3.5,6.5,7.1,10.1,15.9,12.9,17.6,...,11.0,11.4,3.7,3.8,46533,65371,(X),(X),33.3,NaN
14,Indiana,2726489,5.6,3.8,7.1,8.2,12.6,18.0,14.1,16.6,...,9.6,7.7,2.2,1.7,39768,53033,(X),(X),32.2,NaN
15,Iowa,1330995,4.3,3.6,7.5,7.4,12.2,18.4,14.2,17.3,...,10.1,6.9,1.9,2.0,41504,54531,(X),(X),31.5,NaN
16,Kansas,1175294,5.3,3.6,7.5,8.1,11.7,17.8,13.5,16.9,...,8.7,6.9,2.4,2.2,39735,54058,(X),(X),32.3,NaN
17,Kentucky,1828680,6.8,5.8,8.9,8.9,12.4,17.5,12.6,14.9,...,7.9,5.8,1.6,1.7,33993,48151,(X),(X),30.6,NaN
18,Louisiana,1816902,7.9,6.0,10.2,9.4,12.0,16.4,11.5,14.2,...,8.2,6.7,2.1,1.6,32360,47270,(X),(X),35.5,NaN
19,Maine,605338,4.7,4.0,7.6,7.6,11.9,17.6,13.7,17.3,...,10.1,8.2,2.9,2.1,40639,55434,(X),(X),31.2,NaN
20,Maryland,2375984,4.8,2.6,4.9,5.5,8.3,13.5,12.5,18.7,...,12.9,14.4,6.0,5.4,57179,77318,(X),(X),32.8,NaN
21,Massachusetts,2797776,5.2,3.6,5.6,5.6,8.3,12.7,11.3,17.6,...,11.5,13.5,6.4,7.4,55979,82617,(X),(X),34.5,NaN
22,Michigan,4089794,5.7,4.0,7.6,8.1,12.0,17.6,13.2,16.4,...,9.5,8.4,2.5,2.3,40459,56097,(X),(X),33.5,NaN
23,Minnesota,2322190,4.3,3.1,5.6,6.4,9.8,16.3,13.8,19.0,...,11.6,10.7,3.7,3.3,48461,65533,(X),(X),29.8,NaN
24,Mississippi,1148340,8.1,6.4,10.6,9.3,13.2,17.4,12.1,13.2,...,6.4,4.4,1.2,1.4,28667,40989,(X),(X),34.9,NaN
25,Missouri,2521832,5.7,4.4,7.7,8.5,12.3,17.9,13.4,16.2,...,8.9,7.1,1.9,2.1,38435,52852,(X),(X),32.7,NaN
26,Montana,464072,5.0,4.4,7.4,7.8,12.5,17.9,15.0,16.0,...,10.2,7.9,2.1,3.4,40582,58278,(X),(X),32.2,NaN
27,Nebraska,803157,4.9,3.4,7.4,7.6,12.4,17.4,13.5,17.4,...,9.4,7.1,1.7,2.2,40712,54076,(X),(X),30.6,NaN
28,Nevada,1198356,5.6,3.1,6.5,7.4,11.6,17.6,13.6,17.9,...,10.1,10.0,3.0,4.2,46176,66078,(X),(X),34.4,NaN
29,New Hampshire,557220,3.1,2.8,5.3,5.7,8.8,16.0,13.1,18.6,...,11.9,11.3,4.4,5.4,52292,75262,(X),(X),30.2,NaN
30,New Jersey,3516978,4.4,2.9,5.0,5.9,7.9,13.7,11.6,18.1,...,11.6,13.1,5.9,6.2,54589,78512,(X),(X),33.4,NaN
31,New Mexico,848218,7.4,4.9,9.5,9.2,12.1,16.3,12.5,15.6,...,8.7,9.9,2.3,2.6,36532,55207,(X),(X),30.7,NaN
32,New York,7774308,6.8,4.1,6.7,6.5,9.3,14.3,11.6,16.4,...,10.5,11.4,5.1,7.5,50181,78600,(X),(X),36.4,NaN
33,North Carolina,4299266,5.4,4.0,7.4,8.1,12.1,17.7,13.0,16.0,...,9.1,8.9,2.9,2.6,41534,58122,(X),(X),32.6,NaN
34,North Dakota,331481,5.0,4.0,6.6,6.7,11.8,17.6,14.1,17.8,...,11.4,7.5,2.2,2.1,43372,55371,(X),(X),30.9,NaN
35,Ohio,4878206,5.9,4.4,7.5,8.2,12.0,17.8,13.2,16.0,...,9.5,7.8,2.2,2.1,40164,54221,(X),(X),30.7,NaN
36,Oklahoma,1573180,6.4,4.6,9.2,8.8,13.2,18.1,12.4,14.8,...,7.2,6.7,1.8,1.6,35419,49318,(X),(X),34.1,NaN
37,Oregon,1726340,5.1,3.4,6.9,6.7,10.9,16.6,13.3,17.9,...,11.1,11.7,3.9,4.0,48114,66755,(X),(X),28.7,NaN
38,Pennsylvania,5294065,5.5,3.7,7.3,7.7,10.8,16.9,12.6,16.8,...,10.0,9.0,3.1,3.2,42203,60489,(X),(X),32.9,NaN
39,Rhode Island,446688,5.4,4.3,6.2,6.0,8.4,15.5,13.1,19.0,...,12.5,11.5,4.0,3.8,48459,65595,(X),(X),36.3,NaN
40,South Carolina,2136080,6.1,4.2,7.8,8.8,12.6,17.4,13.5,15.6,...,9.2,7.3,2.1,2.3,38426,53647,(X),(X),36.2,NaN
41,South Dakota,368300,5.0,3.8,7.3,7.5,11.5,18.4,14.3,18.2,...,9.0,7.9,2.1,2.6,42028,57250,(X),(X),31.0,NaN
42,Tennessee,2846684,5.4,4.3,7.8,8.2,12.6,18.0,13.3,15.7,...,9.4,7.5,2.6,2.6,40285,56860,(X),(X),34.2,NaN
43,Texas,11087708,5.5,3.6,6.6,7.8,11.0,17.1,12.8,16.2,...,10.3,9.9,3.7,4.0,45999,64874,(X),(X),30.6,NaN
44,Utah,1129660,3.0,2.4,4.1,5.9,9.1,17.0,14.4,21.0,...,12.4,10.4,4.8,3.9,51496,69275,(X),(X),32.3,NaN
45,Vermont,277090,4.0,3.8,6.7,8.1,11.0,17.1,13.8,17.1,...,10.7,8.8,4.3,2.8,46022,63143,(X),(X),31.0,NaN
46,Virginia,3380607,4.9,3.2,5.8,6.1,9.3,14.9,12.2,18.1,...,10.9,12.7,5.4,5.1,51436,73302,(X),(X),32.4,NaN
47,Washington,3079953,4.5,2.8,4.9,5.4,8.8,14.7,13.1,18.9,...,11.7,13.5,5.7,7.7,57299,84851,(X),(X),29.1,NaN
48,West Virginia,736341,7.1,6.3,10.5,9.9,12.5,17.4,12.2,14.2,...,7.3,5.9,1.3,1.9,31082,48384,(X),(X),29.3,NaN
49,Wisconsin,2491121,4.6,3.5,7.0,7.4,12.0,18.1,13.7,18.1,...,10.4,8.8,2.1,2.4,42812,57892,(X),(X),28.7,NaN
50,Wyoming,243321,5.2,3.4,7.5,8.2,11.3,17.7,13.8,18.7,...,10.4,8.2,2.2,3.3,40019,57301,(X),(X),28.8,NaN
51,Puerto Rico,1289311,22.4,10.8,18.2,12.5,12.9,10.8,5.6,3.9,...,2.6,1.7,0.8,0.6,15006,24694,(X),(X),28.2,NaN

In [220]:
# Use a PostgreSQL Relational Database
# Build Postgres Connection

import psycopg2
import pandas as pd

host="13.43.84.151"
dbname="postgres"
user="danyan.guo.20@ucl.ac.uk"
password="y16MAL"
port="5432"
schema="schema_danyanguo20uclacuk"

conn = psycopg2.connect (
    host=host,
    dbname=dbname,
    user=user,
    password=password,
    port=port
)
print("Database connection established")

Database connection established

In [222]:
db_cursor = conn.cursor()

db_cursor = conn.cursor()

schema = "schema"  # Ensure this variable is defined

# Start the CREATE TABLE command, using "Geographic Area Name" as the primary key
create_table_sql = f"""CREATE TABLE IF NOT EXISTS {schema}.income ("""

# Add "State" column as PRIMARY KEY
create_table_sql += '\n    "State" VARCHAR PRIMARY KEY,'

# Add other columns based on data_df, excluding "Geographic Area Name"
for column in household_income_df.columns:
    column_name = column.replace('"', '""').replace(' ', '_').lower()  # Simplify column names
    if column_name != "VARCHAR":  # Exclude the primary key column itself
        create_table_sql += f'\n    "{column_name}" NUMERIC,'

# Remove the trailing comma and close the statement
create_table_sql = create_table_sql.rstrip(',') + '\n);'

db_cursor.execute(create_table_sql)

# Make the changes to the database persistent
conn.commit()

# Make the changes to the database persistent
conn.commit()

InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

In [197]:
from psycopg2.extras import execute_batch

# Reopen the cursor if it's closed
cur = conn.cursor()

# List of columns to insert (excluding any auto-generated primary key, if applicable)
columns_to_insert = household_income_df.columns[0:2]  # Or 'data_df.columns.tolist()' if working with the original DataFrame

# Construct the column names part of the SQL statement
columns_sql = ", ".join([f'"{col}"' for col in columns_to_insert])

# Construct the placeholders part of the SQL statement
values_placeholders = ", ".join(['%s' for col in columns_to_insert])

# Complete INSERT statement
insert_query = f"""
    INSERT INTO {schema}.income({columns_sql})
    VALUES ({values_placeholders})
"""

# Convert the DataFrame to a list of tuples, each representing a row to insert
values = list(household_income_df.itertuples(index=False, name=None))

# Use execute_batch for efficient bulk inserts
execute_batch(cur, insert_query, values)

UndefinedColumn: column "Estimate_Households_Total" of relation "income" does not exist
LINE 2: ...RT INTO schema_danyanguo20uclacuk.income("State", "Estimate_...
                                                             ^